### ISSUE TITLE
Wrong names for starterkit tasks

### ISSUE THREAD

**Issue by yellowled** [pattern-lab/edition-node-grunt#11]
I am using Edition Node Grunt `v2.3.0` on `Mac`, with Node `v4.4.7`.
##### Expected Behavior

According to `grunt patternlab:help`, `grunt patternlab:liststarterkits` should list the available starterkits. `grunt patternlab:loadstarterkit --kit=[starterkit-name]` should copy the starterkit files to `./source/`.
##### Actual Behavior

Both commands/tasks just show the Pattern Lab Node Help.
##### Steps to Reproduce

Enter either `grunt patternlab:liststarterkits` or `grunt patternlab:loadstarterkit --kit=[starterkit-name]`. (Tested in `master` and `dev`.)

Apparently, the proper commands are `grunt patternlab:starterkit-list` and `grunt patternlab:starterkit-load --kit=[starterkit-name]` (figured that out looking at the `Gruntfile.js`). Probably just “legacy documentation” (in the README and `patternlab:help`)?

**Comment by bmuenzenmeyer** [comment]
looks like i missed updating these commands when I changed the signature.

**Comment by tburny** [comment]
I fixed the gruntfile to match the documentation. See https://github.com/pattern-lab/edition-node-grunt/wiki/ChangeLog
