### ISSUE TITLE
Having the ability to include patterns without a prefixed patterntType

### ISSUE THREAD

**Issue by alex-martinez** [pattern-lab/edition-node-grunt#24]
**Summary**
When linking patterns in other patterns it requires the patternType to be prefixed before the pattern.
E.g. `{{> promos-promo-1 }}`
It'd be great if there were a way around this.

**Use Case**
I'm using the `_patterns` folder as a central source for handlebars files to be used in Pattern Lab and in my Yeoman generator. Pattern Lab serves as my documentation and patterns source, while the Yeoman generator is my scaffolding for projects that utilizes the handlebars files in Pattern Lab.

**Issue**
The issue I'm running into is including patterns in other patterns causes errors in my generator because a linked pattern like `{{> promos-promo-1 }}` only works in Pattern Lab.

My current solution is utilizing regex to remove all the prefixes, allowing the original (unprefixed) handlebars file `{{> promo-1 }}` to work.

**Comment by bmuenzenmeyer** [comment]
verbose partial syntax also works

`{{> promos/path/promo-1 }}`
